const StudentActionTypes = {
  FETCH_STUDENT_START: "FETCH_STUDENT_START",
  FETCH_STUDENT_SUCCESS: "FETCH_STUDENT_SUCCESS",
  FETCH_STUDENT_FAILURE: "FETCH_STUDENT_FAILURE",
  DELETE_STUDENT: "DELETE_STUDENT",
  UPDATE_STUDENT: "UPDATE_STUDENT",
  CREATE_STUDENT: "CREATE_STUDENT",
};

export default StudentActionTypes;
