const StudentActionTypes = {
  FETCH_STUDENT_START: "FETCH_STUDENT_START",
  FETCH_STUDENT_SUCCESS: "FETCH_STUDENT_SUCCESS",
  FETCH_STUDENT_FAILURE: "FETCH_STUDENT_FAILURE",

  CREATE_STUDENT: "CREATE_STUDENT",
  CREATE_STUDENT_SUCCESS: "CREATE_STUDENT_SUCCESS",
  CREATE_STUDENT_FAILURE: "CREATE_STUDENT_FAILURE",

  FETCH_STUDENT_BYSTUDENTID_START: "FETCH_STUDENT_BYSTUDENTID_START",
  FETCH_STUDENT_BYSTUDENTID_SUCCESS: "FETCH_STUDENT_BYSTUDENTID_SUCCESS",
  FETCH_STUDENT_BYSTUDENTID_FAILURE: "FETCH_STUDENT_BYSTUDENTID_FAILURE",

  UPDATE_STUDENT: "UPDATE_STUDENT",
  UPDATE_STUDENT_SUCCESS: "UPDATE_STUDENT_SUCCESS",
  UPDATE_STUDENT_FAILURE: "UPDATE_STUDENT_FAILURE",

  DELETE_STUDENT: "DELETE_STUDENT",
  DELETE_STUDENT_SUCCESS: "DELETE_STUDENT_SUCCESS",
  DELETE_STUDENT_FAILURE: "DELETE_STUDENT_FAILURE",
};

export default StudentActionTypes;
