const DesignationtActionTypes = {
  FETCH_DESIGNATIONT_START: "FETCH_DESIGNATIONT_START",
  FETCH_DESIGNATIONT_SUCCESS: "FETCH_DESIGNATIONT_SUCCESS",
  FETCH_DESIGNATIONT_FAILURE: "FETCH_DESIGNATIONT_FAILURE",
  DELETE_DESIGNATIONT: "DELETE_DESIGNATIONT",
  DELETE_DESIGNATIONT_SUCCESS: "DELETE_DESIGNATIONT_SUCCESS",
  DELETE_DESIGNATIONT_FAILURE: "DELETE_DESIGNATIONT_FAILURE",
  UPDATE_DESIGNATIONT: "UPDATE_DESIGNATIONT",
  UPDATE_DESIGNATIONT_SUCCESS: "UPDATE_DESIGNATIONT_SUCCESS",
  UPDATE_DESIGNATIONT_FAILURE: "UPDATE_DESIGNATIONT_FAILURE",
  CREATE_DESIGNATIONT: "CREATE_DESIGNATIONT",
  CREATE_DESIGNATIONT_SUCCESS: "CREATE_DESIGNATIONT_SUCCESS",
  CREATE_DESIGNATIONT_FAILURE: "CREATE_DESIGNATIONT_FAILURE",
};

export default DesignationtActionTypes;
