const DesignationActionTypes = {
  FETCH_DESIGNATION_START: "FETCH_DESIGNATION_START",
  FETCH_DESIGNATION_SUCCESS: "FETCH_DESIGNATION_SUCCESS",
  FETCH_DESIGNATION_FAILURE: "FETCH_DESIGNATION_FAILURE",

  CREATE_DESIGNATION: "CREATE_DESIGNATION",
  CREATE_DESIGNATION_SUCCESS: "CREATE_DESIGNATION_SUCCESS",
  CREATE_DESIGNATION_FAILURE: "CREATE_DESIGNATION_FAILURE",

  FETCH_DESIGNATION_BYDESIGNATIONID_START:
    "FETCH_DESIGNATION_BYDESIGNATIONID_START",
  FETCH_DESIGNATION_BYDESIGNATIONID_SUCCESS:
    "FETCH_DESIGNATION_BYDESIGNATIONID_SUCCESS",
  FETCH_DESIGNATION_BYDESIGNATIONID_FAILURE:
    "FETCH_DESIGNATION_BYDESIGNATIONID_FAILURE",

  UPDATE_DESIGNATION: "UPDATE_DESIGNATION",
  UPDATE_DESIGNATION_SUCCESS: "UPDATE_DESIGNATION_SUCCESS",
  UPDATE_DESIGNATION_FAILURE: "UPDATE_DESIGNATION_FAILURE",

  DELETE_DESIGNATION: "DELETE_DESIGNATION",
  DELETE_DESIGNATION_SUCCESS: "DELETE_DESIGNATION_SUCCESS",
  DELETE_DESIGNATION_FAILURE: "DELETE_DESIGNATION_FAILURE",
};

export default DesignationActionTypes;
