const HomeworkActionTypes = {
  FETCH_HOMEWORK_START: "FETCH_HOMEWORK_START",
  FETCH_HOMEWORK_SUCCESS: "FETCH_HOMEWORK_SUCCESS",
  FETCH_HOMEWORK_FAILURE: "FETCH_HOMEWORK_FAILURE",
};

export default HomeworkActionTypes;
