const HomeworkActionTypes = {
  FETCH_HOMEWORK_START: "FETCH_HOMEWORK_START",
  FETCH_HOMEWORK_SUCCESS: "FETCH_HOMEWORK_SUCCESS",
  FETCH_HOMEWORK_FAILURE: "FETCH_HOMEWORK_FAILURE",

  CREATE_HOMEWORK: "CREATE_HOMEWORK",
  CREATE_HOMEWORK_SUCCESS: "CREATE_HOMEWORK_SUCCESS",
  CREATE_HOMEWORK_FAILURE: "CREATE_HOMEWORK_FAILURE",
};

export default HomeworkActionTypes;
