const HomeworkActionTypes = {
  FETCH_HOMEWORK_START: "FETCH_HOMEWORK_START",
  FETCH_HOMEWORK_SUCCESS: "FETCH_HOMEWORK_SUCCESS",
  FETCH_HOMEWORK_FAILURE: "FETCH_HOMEWORK_FAILURE",

  CREATE_HOMEWORK: "CREATE_HOMEWORK",
  CREATE_HOMEWORK_SUCCESS: "CREATE_HOMEWORK_SUCCESS",
  CREATE_HOMEWORK_FAILURE: "CREATE_HOMEWORK_FAILURE",

  FETCH_HOMEWORK_BYHOMEWORKID_START: "FETCH_HOMEWORK_BYHOMEWORKID_START",
  FETCH_HOMEWORK_BYHOMEWORKID_SUCCESS: "FETCH_HOMEWORK_BYHOMEWORKID_SUCCESS",
  FETCH_HOMEWORK_BYHOMEWORKID_FAILURE: "FETCH_HOMEWORK_BYHOMEWORKID_FAILURE",

  UPDATE_HOMEWORK: "UPDATE_HOMEWORK",
  UPDATE_HOMEWORK_SUCCESS: "UPDATE_HOMEWORK_SUCCESS",
  UPDATE_HOMEWORK_FAILURE: "UPDATE_HOMEWORK_FAILURE",

  DELETE_HOMEWORK: "DELETE_HOMEWORK",
  DELETE_HOMEWORK_SUCCESS: "DELETE_HOMEWORK_SUCCESS",
  DELETE_HOMEWORK_FAILURE: "DELETE_HOMEWORK_FAILURE",
};

export default HomeworkActionTypes;
