const GroupActionTypes = {
  FETCH_GROUP_START: "FETCH_GROUP_START",
  FETCH_GROUP_SUCCESS: "FETCH_GROUP_SUCCESS",
  FETCH_GROUP_FAILURE: "FETCH_GROUP_FAILURE",
  DELETE_GROUP: "DELETE_GROUP",
  DELETE_GROUP_SUCCESS: "DELETE_GROUP_SUCCESS",
  DELETE_GROUP_FAILURE: "DELETE_GROUP_FAILURE",
  UPDATE_GROUP: "UPDATE_GROUP",
  UPDATE_GROUP_SUCCESS: "UPDATE_GROUP_SUCCESS",
  UPDATE_GROUP_FAILURE: "UPDATE_GROUP_FAILURE",
  CREATE_GROUP: "CREATE_GROUP",
  CREATE_GROUP_SUCCESS: "CREATE_GROUP_SUCCESS",
  CREATE_GROUP_FAILURE: "CREATE_GROUP_FAILURE",
};

export default GroupActionTypes;
