const StandardActionTypes = {
  FETCH_STANDARD_START: "FETCH_STANDARD_START",
  FETCH_STANDARD_SUCCESS: "FETCH_STANDARD_SUCCESS",
  FETCH_STANDARD_FAILURE: "FETCH_STANDARD_FAILURE",

  CREATE_STANDARD: "CREATE_STANDARD",
  CREATE_STANDARD_SUCCESS: "CREATE_STANDARD_SUCCESS",
  CREATE_STANDARD_FAILURE: "CREATE_STANDARD_FAILURE",

  FETCH_STANDARD_BYSTANDARDID_START: "FETCH_STANDARD_BYSTANDARDID_START",
  FETCH_STANDARD_BYSTANDARDID_SUCCESS: "FETCH_STANDARD_BYSTANDARDID_SUCCESS",
  FETCH_STANDARD_BYSTANDARDID_FAILURE: "FETCH_STANDARD_BYSTANDARDID_FAILURE",

  UPDATE_STANDARD: "UPDATE_STANDARD",
  UPDATE_STANDARD_SUCCESS: "UPDATE_STANDARD_SUCCESS",
  UPDATE_STANDARD_FAILURE: "UPDATE_STANDARD_FAILURE",

  DELETE_STANDARD: "DELETE_STANDARD",
  DELETE_STANDARD_SUCCESS: "DELETE_STANDARD_SUCCESS",
  DELETE_STANDARD_FAILURE: "DELETE_STANDARD_FAILURE",
};

export default StandardActionTypes;
