const ReplayHomeworkActionTypes = {
  CREATE_REPLAYHOMEWORK: "CREATE_REPLAYHOMEWORK",
  CREATE_REPLAYHOMEWORK_SUCCESS: "CREATE_REPLAYHOMEWORK_SUCCESS",
  CREATE_REPLAYHOMEWORK_FAILURE: "CREATE_REPLAYHOMEWORK_FAILURE",

  FETCH_REPLAYHOMEWORK_BYUSERID_START: "FETCH_REPLAYHOMEWORK_BYUSERID_START",
  FETCH_REPLAYHOMEWORK_BYUSERID_SUCCESS:
    "FETCH_REPLAYHOMEWORK_BYUSERID_SUCCESS",
  FETCH_REPLAYHOMEWORK_BYUSERID_FAILURE:
    "FETCH_REPLAYHOMEWORK_BYUSERID_FAILURE",

  FETCH_REPLAYHOMEWORK_BYREPLAYHOMEWORKID_START:
    "FETCH_REPLAYHOMEWORK_BYREPLAYHOMEWORKID_START",
  FETCH_REPLAYHOMEWORK_BYREPLAYHOMEWORKID_SUCCESS:
    "FETCH_REPLAYHOMEWORK_BYREPLAYHOMEWORKID_SUCCESS",
  FETCH_REPLAYHOMEWORK_BYREPLAYHOMEWORKID_FAILURE:
    "FETCH_REPLAYHOMEWORK_BYREPLAYHOMEWORKID_FAILURE",

  UPDATE_REPLAYHOMEWORK: "UPDATE_REPLAYHOMEWORK",
  UPDATE_REPLAYHOMEWORK_SUCCESS: "UPDATE_REPLAYHOMEWORK_SUCCESS",
  UPDATE_REPLAYHOMEWORK_FAILURE: "UPDATE_REPLAYHOMEWORK_FAILURE",

  DELETE_REPLAYHOMEWORK: "DELETE_REPLAYHOMEWORK",
  DELETE_REPLAYHOMEWORK_SUCCESS: "DELETE_REPLAYHOMEWORK_SUCCESS",
  DELETE_REPLAYHOMEWORK_FAILURE: "DELETE_REPLAYHOMEWORK_FAILURE",
};

export default ReplayHomeworkActionTypes;
