const SubjectActionTypes = {
  FETCH_SUBJECT_START: "FETCH_SUBJECT_START",
  FETCH_SUBJECT_SUCCESS: "FETCH_SUBJECT_SUCCESS",
  FETCH_SUBJECT_FAILURE: "FETCH_SUBJECT_FAILURE",

  CREATE_SUBJECT: "CREATE_SUBJECT",
  CREATE_SUBJECT_SUCCESS: "CREATE_SUBJECT_SUCCESS",
  CREATE_SUBJECT_FAILURE: "CREATE_SUBJECT_FAILURE",

  FETCH_SUBJECT_BYSUBJECTID_START: "FETCH_SUBJECT_BYSUBJECTID_START",
  FETCH_SUBJECT_BYSUBJECTID_SUCCESS: "FETCH_SUBJECT_BYSUBJECTID_SUCCESS",
  FETCH_SUBJECT_BYSUBJECTID_FAILURE: "FETCH_SUBJECT_BYSUBJECTID_FAILURE",

  UPDATE_SUBJECT: "UPDATE_SUBJECT",
  UPDATE_SUBJECT_SUCCESS: "UPDATE_SUBJECT_SUCCESS",
  UPDATE_SUBJECT_FAILURE: "UPDATE_SUBJECT_FAILURE",

  DELETE_SUBJECT: "DELETE_SUBJECT",
  DELETE_SUBJECT_SUCCESS: "DELETE_SUBJECT_SUCCESS",
  DELETE_SUBJECT_FAILURE: "DELETE_SUBJECT_FAILURE",
};

export default SubjectActionTypes;
