const userActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export default userActionTypes;
