const DepartmentActionTypes = {
  FETCH_DEPARTMENT_START: "FETCH_DEPARTMENT_START",
  FETCH_DEPARTMENT_SUCCESS: "FETCH_DEPARTMENT_SUCCESS",
  FETCH_DEPARTMENT_FAILURE: "FETCH_DEPARTMENT_FAILURE",

  CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
  CREATE_DEPARTMENT_SUCCESS: "CREATE_DEPARTMENT_SUCCESS",
  CREATE_DEPARTMENT_FAILURE: "CREATE_DEPARTMENT_FAILURE",

  FETCH_DEPARTMENT_BYDEPARTMENTID_START:
    "FETCH_DEPARTMENT_BYDEPARTMENTID_START",
  FETCH_DEPARTMENT_BYDEPARTMENTID_SUCCESS:
    "FETCH_DEPARTMENT_BYDEPARTMENTID_SUCCESS",
  FETCH_DEPARTMENT_BYDEPARTMENTID_FAILURE:
    "FETCH_DEPARTMENT_BYDEPARTMENTID_FAILURE",

  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  UPDATE_DEPARTMENT_SUCCESS: "UPDATE_DEPARTMENT_SUCCESS",
  UPDATE_DEPARTMENT_FAILURE: "UPDATE_DEPARTMENT_FAILURE",

  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  DELETE_DEPARTMENT_SUCCESS: "DELETE_DEPARTMENT_SUCCESS",
  DELETE_DEPARTMENT_FAILURE: "DELETE_DEPARTMENT_FAILURE",
};

export default DepartmentActionTypes;
