const staffActionTypes = {
  FETCH_STAFFS_START: "FETCH_STAFFS_START",
  FETCH_STAFFS_SUCCESS: "FETCH_STAFFS_SUCCESS",
  FETCH_STAFFS_FAILURE: "FETCH_STAFFS_FAILURE",
  DELETE_STAFF: "DELETE_STAFF",
  UPDATE_STAFF: "UPDATE_STAFF",
  CREATE_STAFF: "CREATE_STAFF",
};

export default staffActionTypes;
