const StaffActionTypes = {
  FETCH_STAFF_START: "FETCH_STAFF_START",
  FETCH_STAFF_SUCCESS: "FETCH_STAFF_SUCCESS",
  FETCH_STAFF_FAILURE: "FETCH_STAFF_FAILURE",

  CREATE_STAFF: "CREATE_STAFF",
  CREATE_STAFF_SUCCESS: "CREATE_STAFF_SUCCESS",
  CREATE_STAFF_FAILURE: "CREATE_STAFF_FAILURE",

  FETCH_STAFF_BYSTAFFID_START: "FETCH_STAFF_BYSTAFFID_START",
  FETCH_STAFF_BYSTAFFID_SUCCESS: "FETCH_STAFF_BYSTAFFID_SUCCESS",
  FETCH_STAFF_BYSTAFFID_FAILURE: "FETCH_STAFF_BYSTAFFID_FAILURE",

  UPDATE_STAFF: "UPDATE_STAFF",
  UPDATE_STAFF_SUCCESS: "UPDATE_STAFF_SUCCESS",
  UPDATE_STAFF_FAILURE: "UPDATE_STAFF_FAILURE",

  DELETE_STAFF: "DELETE_STAFF",
  DELETE_STAFF_SUCCESS: "DELETE_STAFF_SUCCESS",
  DELETE_STAFF_FAILURE: "DELETE_STAFF_FAILURE",
};

export default StaffActionTypes;
